#!/usr/bin/env sh
if [ "$URI" = "" ]; then
echo 'Usage:

export URI=
export PROVIDER=
export LEXICON_CLOUDFLARE_USERNAME=
export LEXICON_CLOUDFLARE_TOKEN=

./dns-01

( for detail info please check http://blog.thesparktree.com/post/138999997429/generating-intranet-and-private-network-ssl )

'
exit 1
fi

docker-compose up
